plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.portfolio.board'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

// mapper.xml을 src로 넣기 위한 코드
sourceSets.main.resources.srcDirs += ["src/main/java"]
sourceSets.test.resources.srcDirs += ["src/test/java"]

//configurations.all {
//	resolutionStrategy {
//		// 'changing' 속성이 true인 모듈(모든 SNAPSHOT은 기본적으로 true)에 대한 캐시 정책
//		// 캐시를 0초 동안만 유효하게 설정. 즉, 빌드 시 항상 최신 버전을 확인하라는 의미.
//		cacheChangingModulesFor 0, 'seconds'
//	}
//}
configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	all{
		resolutionStrategy {
			cacheChangingModulesFor 0, 'seconds'
		}
	}
}

repositories {
	// Nexus 사용
//	maven{
//		// 이 URL은 회사/팀의 Nexus 설정에 따라 달라집니다.
//		// 스냅샷과 릴리즈를 모두 포함하는 group 저장소 URL을 사용하는 것이 일반적입니다.
//		url "$repoUrl/$group"
//		allowInsecureProtocol = true
//		credentials {
//			username "$repoUsername"
//			password "$repoPassword"
//		}
//	}
	// GitHub Packages 사용
	maven{
		name = "GitHubPackages"
		def repoPath = System.getenv("GPR_REPO_PATH") ?: project.findProperty("gpr.sys.path")
		// URL: https://maven.pkg.github.com/{조직명}/{저장소}
		url = "https://maven.pkg.github.com/${repoPath}"
		credentials{
			// CI환경(github actions)과 로컬PC 모두 지원하는 방식
			username = System.getenv("GITHUB_ACTOR") ?: project.findProperty("gpr.user")
			password = System.getenv("GITHUB_TOKEN") ?: project.findProperty("gpr.token")
		}
	}

	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-web'		//
	// 유효성 검증
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// -- JWT 라이브러리 추가 --
	// JWT를 생성하고 검증하기 위한 핵심 라이브러리
	implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	// JWT 서명 알고리즘(e.g., HS256)을 구현한 런타임 라이브러리
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
	// JWT를 JSON으로 변환하거나 그 반대를 위해 필요한 Jackson 라이브러리
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'

	// 공통 라이브러리
	implementation 'com.portfolio.common:system:0.0.1-SNAPSHOT'
	implementation 'com.portfolio.common:business:0.0.1-SNAPSHOT'

	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Add MyBatis
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
	// Add OpenAPI(swagger)
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.6'
	// test, prod를 위한 DI
//	runtimeOnly 'com.oracle.database.jdbc:ojdbc11'
}

tasks.named('test') {
	useJUnitPlatform()
}