# spring: 키 아래에 spring 관련 설정을 그룹화합니다.
spring:
  application:
    name: notic_board
  # h2: 키 아래에 h2 관련 설정을 그룹화합니다.
  h2:
    # console: 키 아래에 h2 콘솔 관련 설정을 그룹화합니다.
    console:
      # H2 데이터베이스 콘솔을 활성화합니다. (http://localhost:8080/h2-console)
      enabled: true
      # H2 콘솔의 접속 경로를 설정합니다.
      path: /h2-console

  # datasource: 키 아래에 데이터소스 관련 설정을 그룹화합니다.
  datasource:
    # JDBC URL: 'testdb'라는 이름의 인메모리 H2 데이터베이스를 사용합니다.
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./data/h2demo
    # 데이터베이스 드라이버 클래스 이름입니다.
    driver-class-name: org.h2.Driver
    # 데이터베이스 접속 사용자 이름입니다.
    username: sa
    # 데이터베이스 접속 비밀번호입니다. (공백)
    password:

  # jpa: 키 아래에 JPA 관련 설정을 그룹화합니다.
  jpa:
    # 데이터베이스 종류에 맞는 SQL을 생성하기 위한 방언(Dialect) 설정입니다.
    database-platform: org.hibernate.dialect.H2Dialect
    # DDL 자동 생성 전략입니다. 애플리케이션 시작 시 테이블을 생성합니다. create, create-drop, update, validate, none(default)
    hibernate:
      ddl-auto: update
    # JPA가 실행하는 SQL 쿼리를 로그로 출력합니다.
    show-sql: true
    # properties: 키 아래에 hibernate의 추가 속성을 설정합니다.
    properties:
      hibernate:
        # 출력되는 SQL 쿼리를 보기 좋게 포맷팅합니다.
        format_sql: true

# Swagger-UI
springdoc:
  # 1. Swagger UI 경로 설정
  swagger-ui:
    path: /swagger # 기본 경로. 변경 가능.
    # 특정 그룹의 API만 필터링하여 보여줄 때 사용
    # tags-sorter: alpha
    # operations-sorter: alpha
  # 2. API 문서(JSON) 경로 설정
  api-docs:
    path: /v1/api # 기본 경로. 변경 가능.
  # 3. 기본 패키지 설정 (선택 사항)
  packages-to-scan: com.portolio.notic_board # 이 패키지 하위의 컨트롤러만 문서화
  # 4. 기본 응답 메시지 설정 (선택 사항)
  # default-produces-media-type: application/json

# OpenAPI 기본 정보 설정
openapi:
  info:
    title: "게시판 프로젝트 API 명세서"
    description: "게시판 서비스 및 Core 개발을 위한 API 문서입니다."
    version: "v1.0.0"
    contact:
      name: "jimiboy"
      email: "200493019@naver.com"
#      url: "https://www.openlabs.co.kr"