name: Deploy to Production

on:
  push:
    branches:  # dev, test, main 브랜치에 push 되면 실행
      [ "dev", "test", "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 설정 (JDK 설치와 Gradle 캐싱을 한 번에 처리)
      - name: Set up JDK 21 and Gralde
        uses: gradle/actions/setup-gradle@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 실행 권한 부여
      #    테스트 코드가 DB에 접속해야 한다면 이 단계에서 환경 변수가 필요.
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Gradle 빌드 및 테스트 (예: Docker 이미지 빌드 후 Push 또는 EC2에 배포)
      #    이 단계에서도 애플리케이션을 실행해야 하므로 동일하게 환경 변수를 주입.
      - name: Build with Gradle
        # env 블록을 통해 GitHub Secret을 환경 변수로 주입.
        run: ./gradlew build
        env:
          DB_PASSWORD: ${{ secrets.BOARD_DB_PASSWORD }}
          HOLIDAY_SERVICE_KEY: ${{ secrets.HOLIDAY_SERVICE_KEY }}
          GPR_SYS_PATH: ${{ secrets.COMM_SYS_PACKAGE_PATH }}
          GPR_BIZ_PATH: ${{ secrets.COMM_BIZ_PACKAGE_PATH }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 빌드 완료 후 'build/libs' 파일 생성 확인 로그 출력
      - name: Check build artifacts
        run: ls -l build/libs

      # --- 배포 시작 ---
      # SCP를 사용하여 JAR 파일을 OCI 서버에 배포
      # appleboy/scp-action 액션을 사용하여 빌드된 JAR 파일을 서버로 복사합니다.
      - name: Create directory on server
        uses: appleboy/ssh-action@master
        with:
          # 서버 주소 (GitHub Secrets에서 가져옴)
          host: ${{ secrets.OCI_SSH_HOST }}
          # 서버 사용자 이름 (GitHub Secrets에서 가져옴)
          username: ${{ secrets.OCI_SSH_USERNAME }}
          # SSH 프라이빗 키 (GitHub Secrets에서 가져옴)
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          script: mkdir -p /home/opc/app
      # JAR 파일 서버로 복사 (scp-action 사용!)
      - name: Deploy JAR to OCI Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_SSH_HOST }}
          username: ${{ secrets.OCI_SSH_USERNAME }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          target: "/home/opc/app"
      # 서버에서 배포 스크립트 실행 (ssh-action 사용!)
      - name: Execute deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_SSH_HOST }}
          username: ${{ secrets.OCI_SSH_USERNAME }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          script: |
            cd /home/opc/app
            if pgrep -f "app.jar" > /dev/null
            then
              echo "Stopping existing application..."
              kill -9 $(pgrep -f "app.jar")
            fi
            mv -f !(*-plain).jar app.jar 2>/dev/null
            echo "Renamed JAR to app.jar"
            rm -f *-plain.jar
            echo "Starting new application..."
            nohup java -jar app.jar > /dev/null 2>&1 &
            echo "Deployment and execution completed."